id=461
title=Atualização openSUSE 11.3 danifica Java
date=2010-12-07 22:03:56
type=post
status=published
tags=FireFox, Java, Linux, openSUSE
~~~~~~

Veja como o http://blog.gilbertoca.com/2010/06/alterne-entre-versoes-java-facilmente-update-alternatives.html[post que menciono o uso do utilitário update-alternatives] é importante.  
Recentemente apliquei um patch - atualização de correção - para o 
http://www.openSUSE.org/pt-br/[openSUSE 11.3] e se não houvesse duas http://www.oracle.com/technetwork/java/javase/downloads/index.html[máquinas virtuais java - JRE -], 
certamente não conseguiria acessar qualquer site que dependesse do http://www.oracle.com/technetwork/java/index.html[Java]. 

Veja o problema:

```
gilberto@dhcppc0:~> firefox -g
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property GtkTreeView::odd-row-color' of typeGdkColor’ from rc file value “((GString*) 0xb1f11100)” of type GString'
*** nss-shared-helper: Shared database disabled (set NSS_USE_SHARED_DB to enable).
ERROR: Invalid browser function table. Some functionality may be restricted.
/usr/src/packages/BUILD/icedtea6-1.9.2/plugin/icedteanp/IcedTeaNPPlugin.cc:1506: thread 0x8090738: Error: Failed to spawn applet viewer: Falha ao executar processo filho "/etc/alternatives/../../bin/java" (Arquivo ou diretório não encontrado)
*** NSPlugin Wrapper *** ERROR: NP_Initialize() wait for reply: Message timeout
ERROR: Invalid browser function table. Some functionality may be restricted.
/usr/src/packages/BUILD/icedtea6-1.9.2/plugin/icedteanp/IcedTeaNPPlugin.cc:1506: thread 0x8090738: Error: Failed to spawn applet viewer: Falha ao executar processo filho "/etc/alternatives/../../bin/java" (Arquivo ou diretório não encontrado)
gilberto@dhcppc0:~>
```

Quando constatei o problema, utilizei o http://transit.iut2.upmf-grenoble.fr/cgi-bin/man/man2html?8+update-alternatives[update-alternatives] para alternar 
a versão da máquina virtual java:

```
gilberto@dhcppc0:~> su -
Senha:
dhcppc0:~ # update-alternatives –config javaplugin
There are 2 alternatives which provide `javaplugin’.
  Selection    Alternative
-----------------------------------------------
 +        1    /usr/lib/jvm/jre-1.6.0-openjdk/lib/i386/IcedTeaPlugin.so
*         2    /usr/lib/jvm/java-1.6.0-sun-1.6.0/jre/lib/i386/libnpjp2.so

Press enter to keep the default[*], or type selection number: 
dhcppc0:~ #
```

Outra solução, caso você só tenha uma versão instalada, se encontra 
http://www.dslreports.com/forum/r24716562-suse-update-broke-java[nesta discussão], pelo comentário do usuário nwrickert. 

**ATUALIZAÇÃO:** esqueci-me de mencionar que está estação de trabalho é a de 
minha casa e que hoje fazem 60 dias que instalei o openSUSE 11.3. Por que está 
nota? Porque os usuários do Windows XP - minha esposa e meu filho(9 anos) - 
adoraram a mudança!