id=386
title=Como recuperar senha de root
date=2010-06-08 11:14:18
type=post
status=published
tags=Console,  Linux, openSUSE
~~~~~~

Não é difícil encontrar novos usuários linux que esquecem ou perdem a senha do http://br-linux.org/artigos/dicas_root.htm[usuário root]
em um servidor ou estação de trabalho. Este post é uma tradução do seguinte HOW-TO: 
http://www.novell.com/support/search.do?cmd=displayKC&#038;docType=kc&#038;externalId=3003803&#038;sliceId=SAL_Public&#038;dialogID=17188705&#038;stateId=0%200%2017194530[Recover the Linux root password], publicado pela novell. 

Então vamos resolver o problema:

  * 1. inicie (Boot) o computador a partir do Cd de instalação;
  * 2. selecione qualquer método de instalação ou a opção recuperação de sistema (Rescue System); 
  * 3. na primeira tela de instalação quando for selecionar a linguagem, pressione **ctrl-alt-f2** para abir um terminal virtual(virtual console); 
====
Se você selecionou recuperação de sistema(Rescue System), selecione a linguagem de seu teclado e então o prompt para o Login de Recuperação(Rescue Login) aparecerá. Entre como root.
====
  * 4. Digite `fdisk -l` para listar as partições. Localize a partição Linux raiz(/). 
    
  * 5. Digite `mount /dev/sda4 /mnt` (substitua sda4 com o nome do dispositivo - device - pela a partição Linux raiz identificada no passo anterior); 
        
  * 6. Execute `mount -o bind /dev /mnt/dev` para tornar os arquivos do dispositivo disponíveis (isso é necessário para o acesso ao dispositivo urandom o qual pode ser usado pelo comando passwd abaixo); 
            
  * 7. Entre `chroot /mnt`

  * 8. Agora entre `passwd root` e digite a nova senha do root;

  * 9. Digite `exit` para sair do ambiente chroot;

  * 10. Desmonte o sistema de arquivos com `umount /mnt`

  * 11. Reinicie o sistema.